name: booking_table
services:
  db:
    image: postgres:14.7
    container_name: postgres
    ports: 
      - 6543:5432
    environment:
      - POSTGRES_DB=bookingsDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bookings_pass132
  backend:
    container_name: backend
    build: .
    ports:
      - 7777:8000
    depends_on:
      - db
    command: ["sh", "run_backend.sh"]
